<a href="https://colab.research.google.com/github/I-Shen/Support-Vector-Machine-Radial-Basis-Function-Kernel-/blob/main/Support_Vector_Machine_(Radial_Basis_Function_Kernel).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT LIBARY

In [ ]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split

# INPUT DATASET

In [ ]:
# pd.set_option('display.float_format', lambda x: f'%.{len(str(x%1))-2}f' % x)
df = pd.read_excel("Bdiabetes.xlsx")
#df = pd.read_csv("Pima indian.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               0      118             64             23       89   0.0   
1               0      102             75             23        0   0.0   
2               0      118             64             23       89   0.0   
3               2       84              0              0        0   0.0   
4               3       80              0              0        0   0.0   
...           ...      ...            ...            ...      ...   ...   
1405            0      129            110             46      130  67.1   
1406            0      129            110             46      130  67.1   
1407            0      129            110             46      130  67.1   
1408            4      183             66              0      215  80.6   
1409            4      183             66              0      215  80.6   

      DiabetesPedigreeFunction  Age  Outcome  
0                        1.731   21        0  
1                        0.572   21        0  
2                        1.731   21        0  
3                        0.304   21        0  
4                        0.174   22        0  
...                        ...  ...      ...  
1405                     0.319   26        1  
1406                     0.319   26        1  
1407                     0.319   26        1  
1408                     0.654   40        0  
1409                     0.654   40        0  

[1410 rows x 9 columns]

# TRAIN TEST SPLIT DATA

In [ ]:
# Generate some sample data
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values


# Define the number of folds
#k = 2

# Shuffle the data
#indices = np.random.permutation(len(X))

#Split the data into k folds
#folds = np.array_split(indices, k)

 #  k-fold cross-validation
#for i in range(k):
     # Select the test and training data for this fold
    #test_indices = folds[i]
    #train_indices = np.concatenate([f for j, f in enumerate(folds) if j != i])
    #X_train, y_train = X[train_indices], y[train_indices]
    #X_test, y_test = X[test_indices], y[test_indices]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=0)

print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[  2.    146.      0.    ...  27.5     0.24   28.   ]
 [  0.     99.      0.    ...  25.      0.253  22.   ]
 [  3.    187.     70.    ...  36.4     0.408  36.   ]
 ...
 [  0.    135.     94.    ...  40.6     0.284  26.   ]
 [  0.    113.     80.    ...  31.      0.874  21.   ]
 [  8.    179.     72.    ...  32.7     0.719  36.   ]]
[[ 12.     92.     62.    ...  27.6     0.926  44.   ]
 [  4.    154.     72.    ...  31.3     0.338  37.   ]
 [  2.    121.     70.    ...  39.1     0.886  23.   ]
 ...
 [  0.     93.    100.    ...  43.4     1.021  35.   ]
 [  0.    163.     40.    ...  40.7     0.322  33.   ]
 [ 11.    138.     74.    ...  36.1     0.557  50.   ]]
[1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0
 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1
 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 0 1 1
 1 0 0 1 1 1 1 0 0 0 1 0 1 1

# NORMALISASI DATA TRAINING

In [ ]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))


# Define the minimum and maximum values for scaling
min_val = np.min(X_train)
max_val = np.max(X_train)

# Apply min-max scaling
norm_training = (X_train - min_val) / (max_val - min_val)

print(X_train)
print(y_train)
print(X_test)
print(y_test)

705
705
705
705
[[  2.    146.      0.    ...  27.5     0.24   28.   ]
 [  0.     99.      0.    ...  25.      0.253  22.   ]
 [  3.    187.     70.    ...  36.4     0.408  36.   ]
 ...
 [  0.    135.     94.    ...  40.6     0.284  26.   ]
 [  0.    113.     80.    ...  31.      0.874  21.   ]
 [  8.    179.     72.    ...  32.7     0.719  36.   ]]
[1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0
 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1
 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 1 0 0 1 0 1 1
 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1
 0 0 1 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 1
 1 0 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 1 1
 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 1

# KERNEL RBF DATA TRAINING

In [ ]:
sigma = 0.001

def rbf(norm_training):
  K = np.zeros((len(norm_training), len(norm_training)))
  for i in range (len(norm_training)):
    for j in range (len(norm_training)):
      #K[i,j] = math.exp(-omega*np.linalg.norm(norm_training[i] - norm_training[j])**2)
      K[i,j] = math.exp(-(np.linalg.norm(((norm_training[i] - norm_training[j])**2)/(2*(sigma**2)))))
  return K

svm = rbf(norm_training)
print(svm)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


# MATRIKS HESSIAN

In [ ]:
ytn=np.zeros(len(y_train))

for y in range(len(y_train)) :
    if y_train[y] == 0 :
        ytn[y] = -1
    else :
        ytn[y] = 1
#print(len(ytn))
#print(y_train)
#print(ytn)

In [ ]:
#print(norm_training)
#print(y_train)
#print(X_test)
#print(y_test)
hessian = np.zeros((len(y_train), len(y_train)))
print(len(hessian))
lambeda = 1
for o in range(len(y_train)):
  for p in range(len(y_train)):
    #if y_train[p] == 0:
    #hessian[o][p] = 1*-1*(svm[o][p]+(lambeda**2))
    hessian[o][p] = ytn[o]*ytn[p]*(svm[o][p]+(lambeda**2))
    #if y_train[p] == 1:
        #hessian[o][p] = 1*1*(svm[o][p]+(lambeda**2))
print(hessian)

705
[[ 2. -1.  1. ... -1. -1.  1.]
 [-1.  2. -1. ...  1.  1. -1.]
 [ 1. -1.  2. ... -1. -1.  1.]
 ...
 [-1.  1. -1. ...  2.  1. -1.]
 [-1.  1. -1. ...  1.  2. -1.]
 [ 1. -1.  1. ... -1. -1.  2.]]


# SEQUENTIAL TRAINING

In [ ]:
iter = 100
t = 0
C = 1
gamma = 0.0001
eps = 0.001
ai = [0]*len(y_train)
dai = [0]*len(y_train)
daitemp = 0
eip = [0]*len(y_train)
ei = np.zeros((len(y_train), len(y_train)))
while t < iter :
  for r in range(len(y_train)):
    for e in range(len(y_train)):
      ei[r][e] = hessian[r][e]*gamma
    eip[r] = np.sum(ei[r][e])
    daitemp = min(max((gamma*(1-eip[r])),ai[r]), C-ai[r])
    if daitemp <= eps:
      dai[r] = daitemp
      ai[r] = ai[r]+dai[r]
    else:
      r = len(y_train)
      t = iter
  t = t + 1
print(dai)
print(ai)
#print(eip)

[0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.00080008, 0.0007999200000000001, 0.0007999200000000001, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.00080008, 0.0007999200000000001, 0.00080008, 0.000799920000

# WX+ WX-

In [ ]:
# rows, cols = (len(y_train), 2)
# positip = [[0]*cols]*rows
# negatip = [[0]*cols]*rows
positip = [0]*len(y_train)
negatip = [0]*len(y_train)
for posneg in range(len(y_train)):
  if y_train[posneg] == 1:
    positip[posneg] = ai[posneg]
    # positip[posneg][1] = y_train[posneg]
  else :
    negatip[posneg] = ai[posneg]
    # negatip[posneg][1] = y_train[posneg]
positip = [h1 for h1 in positip if h1 is not 0]
negatip = [h2 for h2 in negatip if h2 is not 0]
wxplus = max(positip)
wxmin = max(negatip)
#print(positip)
#print(negatip)
print(wxplus)
print(wxmin)
indwxplus = positip.index(wxplus)
indwxmin = negatip.index(wxmin)
print(indwxplus)
print(indwxmin)

0.015984
0.016016
0
0


<>:13: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:13: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-9-7fd7c1c5ee52>:13: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  positip = [h1 for h1 in positip if h1 is not 0]
<ipython-input-9-7fd7c1c5ee52>:14: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  negatip = [h2 for h2 in negatip if h2 is not 0]


# INDEX KERNEL WX+ WX-

In [ ]:
indrbfplus = svm[indwxplus]
indrbfmin = svm[indwxmin]
print(indrbfplus)
print(indrbfmin)

[1.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.000000

 0.00000000e+000]


# TOTAL HASIL WX+ WX-

In [ ]:
h_wxplus = [0]*len(y_train)
h_wxmin = [0]*len(y_train)
for t_wx in range(len(y_train)):
  if y_train[t_wx] == 1:
    h_wxplus[t_wx] = ai[t_wx]*1*indrbfplus[t_wx]
  else :
    h_wxmin[t_wx] = ai[t_wx]*-1*indrbfmin[t_wx]

h_wxplus = [h3 for h3 in h_wxplus if h3 is not 0]
h_wxmin  = [h4 for h4 in h_wxmin if h4 is not 0]

print(h_wxplus)
print(h_wxmin)
#print(ai)

[0.0015998400000000002, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.015009619913477e-43, 5.359146660435178e-113, 0.0, 0.0, 0.0, 5.359146660435178e-113, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.0569842365182625e-258, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.578374318369888e-272, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.578374318369888e-272, 0.0, 3.516904042822745e-91, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.900788052494914e-290, 0.0, 0.0, 0.0, 

<>:9: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:10: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:9: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:10: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-23-0c4783ca568d>:9: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  h_wxplus = [h3 for h3 in h_wxplus if h3 is not 0]
<ipython-input-23-0c4783ca568d>:10: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  h_wxmin  = [h4 for h4 in h_wxmin if h4 is not 0]


# MENGHITUNG NILAI BIAS

In [ ]:
t_wxplus = sum(h_wxplus)
t_wxmin  = sum(h_wxmin)

bias = -0.5*(t_wxplus + t_wxmin)

print(t_wxplus)
print(t_wxmin)
print(bias)

0.015984
-3.598228272040283e-142
-0.007992


# NORMALISASI DATA TESTING

In [ ]:
min_val = np.min(X_test)
max_val = np.max(X_test)

# Apply min-max scaling
norm_test = (X_test - min_val) / (max_val - min_val)

print(norm_test)

[[0.01612903 0.12365591 0.08333333 ... 0.03709677 0.00124462 0.05913978]
 [0.00537634 0.20698925 0.09677419 ... 0.04206989 0.0004543  0.04973118]
 [0.00268817 0.16263441 0.09408602 ... 0.05255376 0.00119086 0.03091398]
 ...
 [0.         0.125      0.1344086  ... 0.05833333 0.00137231 0.04704301]
 [0.         0.21908602 0.05376344 ... 0.0547043  0.0004328  0.04435484]
 [0.01478495 0.18548387 0.09946237 ... 0.04852151 0.00074866 0.0672043 ]]


# KERNEL RBF DATA TESTING

In [ ]:
def rbf_test(norm_training, norm_test):
  T = np.zeros((len(norm_test), len(norm_test)))
  for i in range (len(norm_test)):
    for j in range (len(norm_test)):
      #K[i,j] = math.exp(-omega*np.linalg.norm(norm_training[i] - norm_training[j])**2)
      T[i,j] = math.exp(-(np.linalg.norm(((norm_test[i] - norm_training[j])**2)/(2*(omega**2)))))
  return T

svm_test = rbf_test(norm_training, norm_test)
print(svm)

#def rbf_test(norm_training, norm_test):
  #T =  np.zeros((norm_test.shape[0], norm_test.shape[1]))
  #print(T.shape)
  #for x in range (norm_test.shape[0]):
    #for z in range (norm_test.shape[1]):
      #T[x,z] = math.exp(-(np.linalg.norm(((norm_test[x][z] - norm_training[x][z])**2)/(2*(omega**2)))))
  #return T

#svm_test = rbf_test(norm_training, norm_test)
#print(svm_test)
#print(svm_test.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


# PERHITUNGAN MODEL TEST

In [ ]:
#print(ai)
m_test = np.zeros((len(y_test), len(y_test)))
for v in range(len(y_test)):
  for w in range(len(y_test)):
    if y_train[v] == 0:
      m_test[v][w] =(ai[w])*-1*(svm_test[v][w])
    if y_train[w] == 1:
      m_test[v][w] =(ai[w])*1*(svm_test[v][w])
print(m_test)
print(len(m_test))

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000 -0.00000000e+000  0.00000000e+000 ... -1.36631862e-306
  -0.00000000e+000  1.14687034e-256]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000 -0.00000000e+000  0.00000000e+000 ... -0.00000000e+000
  -0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000 -0.00000000e+000  0.00000000e+000 ... -0.00000000e+000
  -0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]]
705


In [ ]:
h_test = [0]*len(y_test)
for aa in range(len(y_test)):
  h_test[aa] = sum(m_test[aa])

print(h_test)

print(len(y_test))

[0.0, 6.2154065966066e-18, 5.258214679853958e-84, 4.976594303680412e-71, 5.687908774428169e-100, 0.0, 0.031968, -0.016016, 1.0534232484828553e-107, 0.015984, 2.6645804234246174e-129, 0.015984, 0.031968, -0.016016, 0.031968, 2.6052412394e-313, -0.016016, 6.933841127389121e-09, 0.015984, -0.032032, 0.015984, -1.4256745254522278e-21, 0.031968, 2.53203818243e-312, 4.2361260170739943e-91, 0.015984012215993763, 0.015984, -0.016016, -0.016016, 0.0, -5.298029568679321e-62, 1.4182359479935187e-110, 2.724378833449498e-68, -4.9683342463138715e-54, -0.016016, 1.380190290508087e-44, 2.6239470351968094e-14, 0.04795200000000001, 0.0, -2.268687509701972e-25, 7.25484492347683e-150, -0.032032, 0.0, -0.016016, 0.015984, 0.015984, 1.1702921422178939e-35, -0.016016, 0.04795200000000001, 0.031968, 4.344324687368884e-71, -0.016015999999951323, 0.04795200000000001, 0.031995353466997827, -1.6370643737284812e-32, 0.031968, 0.015984, 5.090204143448849e-124, -0.032032, 3.3977194229008656e-93, 1.1989581690471088e-

# PERHITUNGAN PREDIKSI

In [ ]:
hasil_test = [0]*len(y_test)
outcome = [0]*len(y_test)
for bb in range(len(y_test)):
  hasil_test[bb] = h_test[bb]+bias
  if hasil_test[bb] < 0 :
    outcome[bb] = 0
  else:
    outcome[bb] = 1

print(outcome)
print(y_test)
print(hasil_test)
print(len(outcome))
print(len(hasil_test))

[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 

# CONFUSION MATRIKS

In [ ]:
confus = [[0,0],[0,0]]

for f in range(len(y_test)):
  if y_test[f] == 1 and outcome[f] == 1:
    confus[1][1] +=1
  elif y_test[f] == 1 and outcome[f] == 0:
    confus[1][0] +=1
  elif y_test[f] == 0 and outcome[f] == 1:
    confus[0][1] +=1
  elif y_test[f] == 0 and outcome[f] == 0:
    confus[0][0] +=1

tn = confus[0][0]
fn = confus[1][0]
fp = confus[0][1]
tp = confus[1][1]

accuracy = (tn + tp) / (tn+tp+fn+fp)
precision = tp / (tp+fp)
recall = tp / (tp+fn)
f1_score = (2*precision*recall) / (precision+recall)

print(accuracy)
print(precision)
print(recall)
print(f1_score)
print(y_test)
print(outcome)
print(confus[0][0])
print(confus[1][0])
print(confus[0][1])
print(confus[1][1])

0.8354609929078014
1.0
0.6627906976744186
0.7972027972027972
[1 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1
 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1 0 1 1
 1 1 0 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1
 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0
 1 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 0 0 1 0 1 0 1
 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 1 1 0
 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0
 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1
 0 0 0 1 1 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 1 1
 1 1 1 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 0
 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0
 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 